version: 2

build:
  os: ubuntu-lts-latest
  tools:
    # `mambaforge-latest` will now start failing: we just need a working `mamba`
    python: mambaforge-23.11
  commands:
    - git fetch --tags --unshallow
    - mamba install -c conda-forge -c nodefaults pixi==0.44.0
    - pixi run build
    - pixi run docs-lite
    - pixi run docs-mkdocs
    - pixi run -v docs-rtd
