version: 2

build:
  os: ubuntu-lts-latest
  tools:
    # `mambaforge-latest` will now start failing: we just need a working `mamba`
    python: mambaforge-23.11
  commands:
    - git fetch --tags --unshallow
    - mamba install -c conda-forge -c nodefaults pixi==0.44.0
    - pixi run build
    - pixi run test-max-pytest || echo "we tried"
    - pixi run lint-mypy-src || echo "we tried"
    - pixi run docs-lite || echo "we tried"
    - pixi run docs-mkdocs
    - pixi run --skip-deps docs-rtd
