language: python
python:
- '3.6'
- 3.6-dev
- 3.7-dev
install:
- python setup.py sdist
- python setup.py bdist_wheel
- pip install -r requirements.txt
- python -m pip install dist/importnb-*.tar.gz --ignore-installed --no-deps
- echo "Run Python tests\n"
- python -m unittest discover
- pip install -r requirements-test.txt
- mkdir -p tests/PythonDataScienceHandbook/notebooks
- wget https://raw.githubusercontent.com/jakevdp/PythonDataScienceHandbook/master/notebooks/02.02-The-Basics-Of-NumPy-Arrays.ipynb -O tests/PythonDataScienceHandbook/notebooks/_02_The_Basics_Of_NumPy_Arrays.ipynb
script:
- echo "Run IPython tests\n"
- ipython -m unittest discover
- jupyter nbconvert --to markdown --execute --ExecutePreprocessor.kernel_name=python readme.ipynb
# Make the PythonDataScienceHandbook structure
deploy:
  provider: pypi
  user: docfast
  password:
    secure: ry7gJ1HGGEXEzIPAMtWKt1XnoAZ5C642J7/TVFaqEVFT1zukF3wmGL1rqI4h4taq/QhPKznx2NBueySJZZN3vK1wJnfM3pEjroOMQAtrU+W9Y2EKXR4uNFxWSUtqBiuFWkq6IGMC12rPgAjv4U2cDU/HTrezSYKcl5PGZax36wikG7rmEw+UAyPtggWOt4Gcg7vWv6YKzDFW1JIC5qEBEbSxVssmT1uuEKhFSsvl50jmdNukkT+jbFkhjQ0f2cpFwM+Tt+w+eGHAFUxsUQRASwOUDMZK0l43M7eFqqmHZa0XcPQMSrT2lnRcp7yLa9m0WTDHbTnJIEGdw0hBlXXO8GQYcM46cTICFspbtlFFxCnW6+f9mI+y+ONAP/2Gd7/7W1WzfxypcdlnR6XqDgjdd9DzDM+wuTp9IDuSrc6CNGcChs9at0yl83UNZ7t6ikqnw3jc0fKSf7wXP3sHNfDCpCIiEQCgphrOkHa5rHRX+ic9XhzHEoMpTwR71yJHzoFrB6RJZo/8aqifbdqw/VWGt5ESNs6oYUeRjf7oYDPWR86kzY8XlwV5jrr0qZF6eBGe/Bm/pJF3AnHrZkTJVAv84V985g+Mh9XroGksNYG2vKOkGFmCxeqQaZWUHnAYIFtRPamkW7nk+2LUk2hDAGoe5N77BpBVCqUrFR+i+dHbUyM=
  skip_cleanup: true
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: deathbeds/importnb
    python: '3.6'
