
name: Python package
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
        pip install .
    - name: Test  
      run: tox
    - name: Build
      run: |
        python setup.py sdist bdist_wheel
        python -m pip install --find-links=dist --no-index --ignore-installed --no-deps importnb
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: docfast
        password: ${{ secrets.pypi_password }}